# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  nginx:
    profiles: ["https"]
    ports:
      - "8446:443" # host:container (HTTPS)
    volumes:
      - ./docker/nginx/default-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount your certificate and key (e.g., from Let's Encrypt)
      # Ensure these files exist on the host
      - ./docker/nginx/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./docker/nginx/certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro

networks:
  default:
    name: aimer-web_net
